Repository alejandrohdezma/sbt-github, pull requests merged in 2020-04, with the labels that each got.

#116 Update actions, documentation templates and configuration files to v0.9.0
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
  .gitignore
  .mergify.yml
Labels: auto-update

#129 Update sbt-mdoc to 2.1.5
  project/plugins.sbt
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/name-taken-from-display-name/project/plugins.sbt
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/remove-version-timestamp/project/plugins.sbt
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/simple/project/plugins.sbt
Labels: dependency-update

#130 Update http4s to 0.21.3
  build.sbt
Labels: dependency-update

#133 Simplify SBT build
  build.sbt
Labels: enhancement

#134 Enable code-coverage retrieval and uploading to Codecov
  build.sbt
  project/CodeCovPlugin.scala
  project/plugins.sbt
Labels: enhancement

#138 Update actions, documentation templates and configuration files to v0.10.0
  .github/workflows/changelog.yml
Labels: auto-update

#140 Fix & Refactor `Collaborator` constructors
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/SbtGithubPlugin.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/Collaborator.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/Repository.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/urls/RepositoryEntryPoint.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/urls/UserEntryPoint.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/CollaboratorsSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/RepositorySpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/urls/RepositoryEntryPointSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/urls/UserEntryPointUrlSpec.scala
Labels: bug

#142 Enable indicating the whole path when retrieving nested values in JSON
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/Repository.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/http/client.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/json/Decoder.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/json.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/scalatry.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/JsonSyntaxSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/TrySyntaxSpec.scala
Labels: enhancement

#146 Add `per_page` query param to contributors and collaborators URLs
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/Repository.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/url.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/UrlSyntaxSpec.scala
Labels: enhancement

#151 Add `sbt-remove-test-from-pom` plugin
  project/RemoveTestFromPomPlugin.scala
  project/plugins.sbt
Labels: enhancement

#157 Add `sbt-codecov` plugin
  project/CodeCovPlugin.scala
  project/plugins.sbt
Labels: enhancement

#159 Add new `DESCRIPTION` mdoc variable with `description` setting value
  docs/README.md
  sbt-github-mdoc/src/main/scala/com/alejandrohdezma/sbt/github/mdoc/SbtGithubMdocPlugin.scala
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/simple/DOCS.md
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/simple/docs/DOCS.md
Labels: enhancement

#160 Update actions, documentation templates and configuration files to v0.11.0
  .github/labels.yml
  .github/pr-labeler.yml
Labels: auto-update

#165 Update actions, documentation templates and configuration files to v0.12.0
  .github/pr-labeler.yml
Labels: auto-update

#170 Update sbt-fix to 0.5.0
  project/plugins.sbt
  sbt-github-header/src/main/scala/com/alejandrohdezma/sbt/github/sbtheader/SbtGithubHeaderPlugin.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/SbtGithubPlugin.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/Collaborator.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/Repository.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/github/urls/UserEntryPoint.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/http/client.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/json/Decoder.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/json.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/list.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/scalatry.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/throwable.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/syntax/url.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/http/ClientSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/json/DecoderSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/package.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/TrySyntaxSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/UrlSyntaxSpec.scala
Labels: dependency-update

#175 Update `sbt-codecov` to version `0.1.1`
  project/plugins.sbt
Labels: dependency-update

#178 Add `githubEnabled` setting to be used instead of `downloadInfoFromGithub`
  README.md
  build.sbt
  docs/README.md
  sbt-github-header/src/sbt-test/sbt-github-header/create-agpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-apache-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd2-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd3-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-gpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-lgpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-mit-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-mpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/fail-if-no-license/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/fail-if-no-year-range/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/fail-if-unable-to-infer-license/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-license-style-setting/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-organization-name-and-homepage-as-copyright-owner/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-organization-name-as-copyright-owner/build.sbt
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/remove-version-timestamp/build.sbt
  sbt-github-mdoc/src/sbt-test/sbt-github-mdoc/simple/build.sbt
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/SbtGithubPlugin.scala
  sbt-github/src/sbt-test/sbt-github/enable-github/build.sbt
  sbt-github/src/sbt-test/sbt-github/enable-github/project/plugins.sbt
  sbt-github/src/sbt-test/sbt-github/enable-github/test
  sbt-github/src/sbt-test/sbt-github/excluded-contributors/build.sbt
  sbt-github/src/sbt-test/sbt-github/extra-collaborators/build.sbt
  sbt-github/src/sbt-test/sbt-github/not-use-owner/build.sbt
  sbt-github/src/sbt-test/sbt-github/simple/build.sbt
Labels: enhancement

#179 Move minimum version of `sbt-header` to `5.6.0`
  README.md
  build.sbt
  docs/README.md
  project/plugins.sbt
  sbt-github-header/src/main/scala/com/alejandrohdezma/sbt/github/sbtheader/SbtGithubHeaderPlugin.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-agpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-agpl-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-agpl-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-agpl-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-agpl-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/create-apache-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd2-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd2-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd2-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd2-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd2-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd3-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd3-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd3-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd3-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-bsd3-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/create-gpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-gpl-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-gpl-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-gpl-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-gpl-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/create-lgpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-lgpl-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-lgpl-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-lgpl-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-lgpl-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/create-mit-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-mit-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-mit-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-mit-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-mit-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/create-mpl-headers-with-downloaded-info/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-mpl-headers-with-downloaded-info/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/create-mpl-headers-with-downloaded-info/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/create-mpl-headers-with-downloaded-info/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/create-mpl-headers-with-downloaded-info/test
  sbt-github-header/src/sbt-test/sbt-github-header/fail-if-no-license/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/fail-if-no-year-range/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/fail-if-unable-to-infer-license/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-license-style-setting/build.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-license-style-setting/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-license-style-setting/src/main/resources/MyFile.scala_expected
  sbt-github-header/src/sbt-test/sbt-github-header/use-license-style-setting/src/main/scala/MyFile.scala
  sbt-github-header/src/sbt-test/sbt-github-header/use-license-style-setting/test
  sbt-github-header/src/sbt-test/sbt-github-header/use-organization-name-and-homepage-as-copyright-owner/project/plugins.sbt
  sbt-github-header/src/sbt-test/sbt-github-header/use-organization-name-as-copyright-owner/project/plugins.sbt
Labels: enhancement

#181 Update Scala, SBT & plugins to latest version
  build.sbt
  project/build.properties
  project/plugins.sbt
Labels: dependency-update

#183 Update sbt-ci-release to 1.5.3
  project/plugins.sbt
Labels: scala-steward

#184 Deprecate `githubToken` in favour of `githubAuthToken`
  build.sbt
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/SbtGithubPlugin.scala
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/http/Authentication.scala
Labels: enhancement

#185 Add microsite
  .github/workflows/docs.yml
  README.md
  build.sbt
  docs/README.md
  microsite/docs/docs/adding-extra-collaborators.md
  microsite/docs/docs/excluding-contributors.md
  microsite/docs/docs/getting-started.md
  microsite/docs/docs/github-token.md
  microsite/docs/docs/owner-as-organization.md
  microsite/docs/docs/sbt-header.md
  microsite/docs/docs/sbt-mdoc.md
  microsite/docs/index.md
  microsite/settings.sbt
  microsite/src/main/resources/microsite/css/style.css
  microsite/src/main/resources/microsite/data/menu.yml
  microsite/src/main/resources/microsite/img/light-navbar-brand.svg
  microsite/src/main/resources/microsite/img/light-sidebar-brand.svg
  project/plugins.sbt
Labels: documentation

#186 Change `specs2` to `munit` as test framework
  build.sbt
  sbt-github/src/test/resources/log4j2.xml
  sbt-github/src/test/resources/logback-test.xml
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/CollaboratorsSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/CollaboratorsSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/ContributorsSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/RepositorySpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/UserSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/repository/RepositoryCollaboratorsSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/repository/RepositoryContributorsSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/repository/RepositoryOrganizationSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/repository/RepositoryOwnerSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/repository/RepositorySuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/repository/package.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/urls/RepositoryEntryPointSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/github/urls/UserEntryPointUrlSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/http/ClientSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/json/DecoderSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/json/DecoderSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/json/JsonSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/json/JsonSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/package.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/JsonSyntaxSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/JsonSyntaxSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/TrySyntaxSpec.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/TrySyntaxSuite.scala
  sbt-github/src/test/scala/com/alejandrohdezma/sbt/github/syntax/UrlSyntaxSuite.scala
Labels: tests

#189 Support `scala-steward` `scmInfo`
  sbt-github/src/main/scala/com/alejandrohdezma/sbt/github/SbtGithubPlugin.scala
  sbt-github/src/sbt-test/sbt-github/override-organization/build.sbt
Labels: enhancement
